// import React from "react";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Image from "next/image";
// import { AuthContextProvider } from "./shared/context/auth-context"; // corrected import

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <AuthContextProvider>{children}</AuthContextProvider>
//         <footer className="footer_container  bg-slate-800">
//           <div className="flex pr-4 justify-end">
//             <Image
//               src="/logo_gennyconnect.png"
//               alt="footer"
//               width={30}
//               height={30}
//               className="mr-3"
//             />
//             <p>© 2024 GennyConnect. All rights reserved</p>
//           </div>
//           <div className="flex justify-between align-middle w-1/2">
//             <p>Cookies settings</p>
//             <p>Sitemap</p>
//             <p>Privacy policy</p>
//             <p>Terms of use</p>
//           </div>
//         </footer>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { AuthProvider } from "./shared/context/auth-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider> {children}</AuthProvider>
        <footer className="footer_container bg-slate-800">
          <div className="flex pr-4 justify-end">
            <Image
              src="/logo_gennyconnect.png"
              alt="footer"
              width={30}
              height={30}
              className="mr-3"
            />
            <p>© 2024 GennyConnect. All rights reserved</p>
          </div>
          <div className="flex justify-between align-middle w-1/2">
            <p>Cookies settings</p>
            <p>Sitemap</p>
            <p>Privacy policy</p>
            <p>Terms of use</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
